# -*- coding: cp1252 -*-
# ---------------------------------------------------------------------------
# TIME.py
# Created on: 2021-01-22 10:21:58.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------
#   "C:\Python27\ArcGISx6410.7\\PYTHON.exe" "E:\\scripts-arcgis\\Puntos_Calientes\\TIME5.py"
# Import arcpy module
import arcpy
from string import Template


Recorte_shp = "E:\\scripts-arcgis\\Puntos_Calientes\\Piloto_IF\\Proceso\\Recorte.shp"
Recorte2_shp = "E:\\scripts-arcgis\\Puntos_Calientes\\Piloto_IF\\Proceso2\\Recorte2.shp"
GDB_PATH = "E:\\scripts-arcgis\\sde\\puntos_calientes_197.sde"
#GDB_PATH = "E:\\scripts-arcgis\\sde\\puntos_calientes_214.sde"
puntos_calientes_sde_puntos_diarios_con_fecha = GDB_PATH + "\\puntos_calientes.sde.puntos_diarios_con_fecha"


# Process: Copy Features
arcpy.CopyFeatures_management(Recorte_shp, Recorte2_shp, "", "0", "0", "0")

# Process: Add Field
arcpy.AddField_management(Recorte2_shp, "TIME", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(Recorte2_shp, "TIME", "!ACQ_TIME!", "PYTHON_9.3", "")

# Process: Add Field
arcpy.AddField_management(Recorte2_shp, "GTM_VER", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(Recorte2_shp, "GTM_VER", "300", "PYTHON_9.3", "")

# Process: Add Field
arcpy.AddField_management(Recorte2_shp, "HORA1", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(Recorte2_shp, "HORA1", "!TIME! - !GTM_VER!", "PYTHON_9.3", "")

# Process: Add Field
arcpy.AddField_management(Recorte2_shp, "HORA2", "TEXT", "", "", "10", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(Recorte2_shp, "HORA2", "!HORA1!", "PYTHON_9.3", "")

# Process: Add Field
arcpy.AddField_management(Recorte2_shp, "HORA3", "TEXT", "", "", "10", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(Recorte2_shp, "HORA3", "!HORA2!.zfill(4)", "PYTHON_9.3", "")

# Process: Add Field
arcpy.AddField_management(Recorte2_shp, "FECHA", "TEXT", "", "", "20", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(Recorte2_shp, "FECHA", "!ACQ_DATE!", "PYTHON_9.3", "")

# Process: Add Field
arcpy.AddField_management(Recorte2_shp, "HOUR", "TEXT", "", "", "3", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(Recorte2_shp, "HOUR", "!HORA3![0:2]", "PYTHON_9.3", "")

# Process: Add Field
arcpy.AddField_management(Recorte2_shp, "MIN", "TEXT", "", "", "3", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(Recorte2_shp, "MIN", "!HORA3![2:4]", "PYTHON_9.3", "")

# Process: Add Field
arcpy.AddField_management(Recorte2_shp, "HORA_VERAN", "TEXT", "", "", "10", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(Recorte2_shp, "HORA_VERAN", "!HOUR!+\":\"+ !MIN!", "PYTHON_9.3", "")

# Process: Delete Field
arcpy.DeleteField_management(Recorte2_shp, "TIME;GTM_VER;HORA1;HORA2;HORA3;HOUR;MIN")

# Process: Delete Rows
arcpy.DeleteRows_management(puntos_calientes_sde_puntos_diarios_con_fecha)

# Local variables
field_mapping_text = Template(
    "latitude \"latitude\" true true false 8 Double 10 18 ,First,#,$path_cd,LATITUDE,-1,-1;longitude \"longitude\" true true false 8 Double 10 18 ,First,#,$path_cd.shp,LONGITUDE,-1,-1;bright_ti4 \"bright_ti4\" true true false 8 Double 10 18 ,First,#,$path_cd,BRIGHT_TI4,-1,-1;scan \"scan\" true true false 8 Double 10 18 ,First,#,$path_cd,SCAN,-1,-1;track \"track\" true true false 8 Double 10 18 ,First,#,$path_cd,TRACK,-1,-1;acq_date \"acq_date\" true true false 8 Date 0 0 ,First,#,$path_cd,ACQ_DATE,-1,-1;acq_time \"acq_time\" true true false 4 Text 0 0 ,First,#,$path_cd,ACQ_TIME,-1,-1;satellite \"satellite\" true true false 1 Text 0 0 ,First,#,$path_cd,SATELLITE,-1,-1;confidence \"confidence\" true true false 7 Text 0 0 ,First,#,$path_cd,CONFIDENCE,-1,-1;version \"version\" true true false 6 Text 0 0 ,First,#,$path_cd,VERSION,-1,-1;bright_ti5 \"bright_ti5\" true true false 8 Double 10 18 ,First,#,$path_cd,BRIGHT_TI5,-1,-1;frp \"frp\" true true false 8 Double 10 18 ,First,#,$path_cd,FRP,-1,-1;daynight \"daynight\" true true false 1 Text 0 0 ,First,#,$path_cd,DAYNIGHT,-1,-1;fecha \"fecha\" true true false 20 Text 0 0 ,First,#,$path_cd,FECHA,-1,-1;hora_veran \"hora_veran\" true true false 10 Text 0 0 ,First,#,$path_cd,HORA_VERAN,-1,-1;globalid \"globalid\" false false false 38 GlobalID 0 0 ,First,#"
).substitute(path_cd=Recorte2_shp)

# Process: Append
arcpy.Append_management(
    Recorte2_shp,
    puntos_calientes_sde_puntos_diarios_con_fecha,
    "NO_TEST",
    field_mapping_text,
    ""
)


# Process: Delete
arcpy.Delete_management(Recorte2_shp, "ShapeFile")

