# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Publicacion_shakemap_gdb.py
# Created on: 2019-02-27 11:23:44.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------
#ejecutar desde cmd
# "C:\Python27\ArcGIS10.3\python.exe" "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\Python\Proceso_Publicación_ShakeMap_SE.py"

# Import arcpy module
import arcpy

print "Borra correctamente shakemap de la gdb"
# Local variables:
shakemap = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Importa_shake.gdb\\shakemap"
La_eliminacion_se_realizo_correctamente__2_ = "true"

# Process: Eliminar (2)
arcpy.Delete_management(shakemap, "RasterDataset")

print "Borra correctamente shakemap_entero de la gdb"
# Local variables:
shakemap_entero = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Importa_shake.gdb\\shakemap_entero"
La_eliminacion_se_realizo_correctamente__2_ = "true"

# Process: Eliminar (2)
arcpy.Delete_management(shakemap_entero, "RasterDataset")

print "Borra correctamente el shakemap_poligono.shp"
# Local variables:
shakemap_poligono_shp = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Shake_Poligono\\shakemap_poligono.shp"
La_eliminacion_se_realizo_correctamente__2_ = "true"

# Process: Eliminar (2)
arcpy.Delete_management(shakemap_poligono_shp, "ShapeFile")

print "Borra correctamente el poligono_disuelto.shp"
# Local variables:
poligono_disuelto_shp = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Shake_Disuelto\\poligono_disuelto.shp"
La_eliminacion_se_realizo_correctamente__2_ = "true"

# Process: Eliminar (2)
arcpy.Delete_management(poligono_disuelto_shp, "ShapeFile")

print "Borra correctamente el shakemap_cortado.shp"
# Local variables:
shakemap_cortado_shp = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Shake_Cortado\\shakemap_cortado.shp"
La_eliminacion_se_realizo_correctamente__2_ = "true"

# Process: Eliminar (2)
arcpy.Delete_management(shakemap_cortado_shp, "ShapeFile")

print "Borra correctamente el shakemap_cortado_disuelto.shp"
# Local variables:
shakemap_cortado_disuelto_shp = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Shake_Cortado\\shakemap_cortado_disuelto.shp"
La_eliminacion_se_realizo_correctamente = "false"

# Process: Eliminar
arcpy.Delete_management(shakemap_cortado_disuelto_shp, "ShapeFile")

print "Importa correctamente el shakemap a la BD.gdb"
# Local variables:
shakemap_grd = "C:\sismologia\SHAKEMAP_ENTRADA\shakemap.grd"
Importa_shake_gdb__2_ = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Importa_shake.gdb"
Importa_shake_gdb__4_ = Importa_shake_gdb__2_

# Process: De ráster a geodatabase
arcpy.RasterToGeodatabase_conversion("C:\sismologia\SHAKEMAP_ENTRADA\shakemap.grd", Importa_shake_gdb__2_, "")

print "Transforma correctamente shakemap de ráster a poligono"
# Process: De ráster a polígono
arcpy.RasterToPolygon_conversion(shakemap, shakemap_poligono_shp, "NO_SIMPLIFY", "Value")

# Local variables:
shakemap_poligono_shp = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Shake_Poligono\\shakemap_poligono.shp"
shakemap_poligono_shp__2_ = shakemap_poligono_shp

print "Define correctamente la proyección del shakemap poligono"
# Process: Definir proyección
arcpy.DefineProjection_management(shakemap_poligono_shp, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

# Local variables:
Importa_shake_gdb__2_ = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Importa_shake.gdb"
shakemap_poligono_shp = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Shake_Poligono\\shakemap_poligono.shp"
poligono_disuelto_shp = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Shake_Disuelto\\poligono_disuelto.shp"
shake_shp__2_ = "C:\\Users\\Administrador\\Documents\\Shakemap\\Poligono\\shake.shp"

print "disuelve correctamente el shakemap poligono"
# Process: Disolver
arcpy.Dissolve_management(shakemap_poligono_shp, poligono_disuelto_shp, "GRIDCODE", "", "MULTI_PART", "DISSOLVE_LINES")

# Local variables:
Importa_shake_gdb__2_ = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Importa_shake.gdb"
poligono_disuelto_shp = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Shake_Disuelto\\poligono_disuelto.shp"
poligono_disuelto_shp__2_ = poligono_disuelto_shp
Intensidad_dbf = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Join\\Intensidad.dbf"

print "Asocia correctamente la simbología"
# Process: Campo de unión
arcpy.JoinField_management(poligono_disuelto_shp, "GRIDCODE", Intensidad_dbf, "GRIDCODE", "GRIDCODE;INTENS_INS")

# Local variables:
Importa_shake_gdb__2_ = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Importa_shake.gdb"
poligono_disuelto_shp = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Shake_Disuelto\\poligono_disuelto.shp"
DPA_shp = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Clip\\DPA.shp"
shakemap_cortado_shp = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Shake_Cortado\\shakemap_cortado.shp"

print "Recorta correctamente el océano del shakemap poligono"
# Process: Recortar
arcpy.Clip_analysis(poligono_disuelto_shp, DPA_shp, shakemap_cortado_shp, "")

# Local variables:
shakemap_cortado_shp = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Shake_Cortado\\shakemap_cortado.shp"
shakemap_cortado_disuelto_shp = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Shake_Cortado\\shakemap_cortado_disuelto.shp"

print "disuelve correctamente la simbología"
# Process: Disolver
arcpy.Dissolve_management(shakemap_cortado_shp, shakemap_cortado_disuelto_shp, "INTENS_INS", "", "MULTI_PART", "DISSOLVE_LINES")

# Local variables:
shakemap_sde_shakemap = "Database Connections\\Shakemap.sde\\shakemap.sde.shakemap"
shakemap_sde_shakemap__2_ = shakemap_sde_shakemap

# Process: Delete Rows
arcpy.DeleteRows_management(shakemap_sde_shakemap)

print "Elimina correctamente los registros de la BD .SDE"


# Local variables:
shakemap_cortado_disuelto_shp = "C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Shake_Cortado\\shakemap_cortado_disuelto.shp"
shakemap_sde_shakemap__2_ = shakemap_cortado_disuelto_shp
shakemap_sde_shakemap = "Database Connections\\Shakemap.sde\\shakemap.sde.shakemap"

# Process: Append
arcpy.Append_management("C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Shake_Cortado\\shakemap_cortado_disuelto.shp", shakemap_sde_shakemap, "NO_TEST", "intens_ins \"intens_ins\" true true false 254 Text 0 0 ,First,#,C:\\Users\\Administrador\\Documents\\SHAKEMAP_2019\\Shake_Cortado\\shakemap_cortado_disuelto.shp,INTENS_INS,-1,-1;st_area(shape) \"st_area(shape)\" false false true 0 Double 0 0 ,First,#;st_length(shape) \"st_length(shape)\" false false true 0 Double 0 0 ,First,#", "")
print "incorpora correctamente los nuevos registros a la BD .SDE"

print "elimina shakemap.grd de la carpeta entrada"

# Local variables:
shakemap_grd = "C:\\sismologia\\SHAKEMAP_ENTRADA\\shakemap.grd"
Delete_succeeded = "false"

# Process: Delete
arcpy.Delete_management(shakemap_grd, "RasterDataset")

print "shakemap.grd eliminado"
